### ISSUE TITLE
Failed build on macOS 12.5

### ISSUE THREAD

**Issue by tuduongquyet** [tboox/tbox#195]
### Describe the bug
Failed build on macOS 12.5, XCode 13.4

### Expected behavior
Build source code
### Error output
```
[ 89%]: ccache compiling.release src/demo/container/bloom_filter.c
[ 89%]: ccache compiling.release src/demo/container/hash_map.c
[ 89%]: ccache compiling.release src/demo/algorithm/sort.c
[ 89%]: ccache compiling.release src/demo/algorithm/find.c
error: src/demo/platform/poller_pipe.c:70:15: error: variable 'total' set but not used [-Werror,-Wunused-but-set-variable]
    tb_hize_t total = 0;
              ^
1 error generated.
```

### Related Environment
macOS 12.5
XCode 13.4

**Comment by waruqi** [comment]
I have fixed it.

**Comment by tuduongquyet** [comment]
> I have fixed it.

Thank youuu
